### ISSUE TITLE
provide a way to ignore files

### ISSUE THREAD

**Issue by maksym-arutyunyan** [lusingander/cargo-sort-derives#1]
Certain files in the repository, such as third-party code or automatically generated files (e.g., protobuf-to-Rust conversions), should not be modified. Integrating CI tools to both verify that the protobuf-to-Rust conversion generates correct code and to adjust Rust derives may lead to conflicts, which is undesirable. Therefore, it is necessary to have a mechanism for excluding specific files from such processes.

P.S. thank you for creating this tool!

FYI:
1. https://sort-derive-traits.github.io
2. https://github.com/maksym-arutyunyan/keepsorted

**Comment by maksym-arutyunyan** [comment]
An extra suggestion is to ignore files listed in `.gitignore`. 
I am using this approach in my CI, see [example](https://github.com/maksym-arutyunyan/keepsorted/blob/2499b831ada1b103b9d3801667ddbc936b8a60f5/.github/workflows/workflow.yaml#L142).

**Comment by lusingander** [comment]
> An extra suggestion is to ignore files listed in .gitignore.

It seems to be already implemented. It might be good to update the documentation or allow users to choose.

**Comment by lusingander** [comment]
Supported in [v0.5.0](https://github.com/lusingander/cargo-sort-derives/releases/tag/v0.5.0)
