### ISSUE TITLE
sort by the last token ignoring namespace prefix

### ISSUE THREAD

**Issue by maksym-arutyunyan** [lusingander/cargo-sort-derives#2]
In some cases users provide namespace prefixes for derive traits (eg. `serde::Deserialize` or `std::fmt::Debug`) which can put that trait in a different position (depending on the prefix). It would be nice to sort traits ignoring the prefix.

See as example https://github.com/maksym-arutyunyan/keepsorted/pull/30.

**Comment by lusingander** [comment]
I think it's already implemented like that. Can you provide a specific example of a problem?

**Comment by maksym-arutyunyan** [comment]
```rs
// Original:
#[derive(serde::Serialize, Unknown, Ord, Clone, c, b, a, C, B, A, Serialize)]
struct Data {}

// Modified:
#[derive(A, B, C, Clone, Ord, serde::Serialize, Serialize, Unknown, a, b, c)]
struct Data {}
```

I would expect to see `Serialize` before `serde::Serialize` because I assume it sorts first by the last token and then by the whole string if tokens are the same, eg. `(last_token_a, whole_string_a).cmp(&(last_token_b, whole_string_b))`. For example like [here](https://github.com/maksym-arutyunyan/keepsorted/blob/19a90d195ae39feb96f8884d5ba401c81432a18a/src/strategies/rust_derive.rs#L134).

**Comment by lusingander** [comment]
I still don't quite understand the behavior you're expecting. Does this mean that prefix should be taken into consideration, unlike issue title?

**Comment by maksym-arutyunyan** [comment]
Sorting should be performed first by the last token. 
In cases where the last tokens are identical, the sorting must be based on the entire string.

For example:
```rs
// Input
#[derive(b::Serialize, Serialize, a::Serialize, C, B, A)]
struct Data {}

// Current
#[derive(A, B, C, b::Serialize, Serialize, a::Serialize)]
struct Data {}

// Expected
#[derive(A, B, C, Serialize, a::Serialize, b::Serialize)]
struct Data {}
```

**Comment by lusingander** [comment]
Ah, I see, I understand now. It certainly would be better to sort explicitly to fix the order.

**Comment by maksym-arutyunyan** [comment]
please take a look at https://github.com/lusingander/cargo-sort-derives/pull/5

**Comment by lusingander** [comment]
https://github.com/lusingander/cargo-sort-derives/releases/tag/v0.6.0
