### ISSUE TITLE
provide a way to run on a specific file

### ISSUE THREAD

**Issue by maksym-arutyunyan** [lusingander/cargo-sort-derives#4]
This request should be separate from the "ignoring files" feature, though it addresses a similar issue. When a repository contains third-party or automatically generated Rust code, developers need a way to exclude those files from modification. By adding a `-p` or `--path` argument, the tool can be executed on specific files. The selection of files can then be managed through shell scripting.

Eg. in [this PR](https://github.com/dfinity/ic/pull/1241) protobuf-rust files were ignored by running the script on a specific set of files selected by a custom shell script.

**Comment by lusingander** [comment]
https://github.com/lusingander/cargo-sort-derives/releases/tag/v0.8.0
