### ISSUE TITLE
change order field in config file to be a list of strings

### ISSUE THREAD

**Issue by maksym-arutyunyan** [lusingander/cargo-sort-derives#6]
Switch the type of `order` configuration field from a string to an array of strings.
Or provide an alternative field (if not possible otherwise).
This improves readability and allows to add clarifying comments in between items.

Before:
```toml
order = "Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Display, Default, Foo, Bar"
```

After:
```toml
order = [
    # Standard traits in the order provided in Rust API guidelines,
    # see https://rust-lang.github.io/api-guidelines/interoperability.html
    "Copy",
    "Clone",
    "Eq",
    "PartialEq",
    "Ord",
    "PartialOrd",
    "Hash",
    "Debug",
    "Display",
    "Default",

    # Company specific traits.
    "Foo",
    "Bar",

    # All the rest will preserve their original order.
]
```

**Comment by lusingander** [comment]
Yes, I thought that would be better.
However, rather than switching or providing an alternative field, I thought it would be better to be able to accept both formats.

**Comment by lusingander** [comment]
https://github.com/lusingander/cargo-sort-derives/releases/tag/v0.7.0
